config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root to: 'static_pages#home'
    get 'help', to: 'static_pages#help'

    resources :cars, only: :index
    resources :searches, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  MIN_YEAR = 1884

  validates :make, :model, presence: true, length: { maximum: 70 }
  validates :description, presence: true, length: { maximum: 400 }
  validates :year, presence: true, inclusion: { in: MIN_YEAR..Date.current.year }, numericality: true
  validates :odometer, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user, optional: true

  validates :requests_quantity, presence: true, numericality: { greater_than_or_equal_to: 1, default: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :searches, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  private

  def default_url_options
    { locale: I18n.locale }
  end

  def switch_locale(&)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars_collection = CarQuery.new.call(index_params)
  end

  private

  def index_params
    params.permit(:page, :items, :make, :model, :price_from, :price_to, :year_from, :year_to, :order_by, :direction)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
    @user_search_collection = SearchQuery.new(user_searches).call(query_params)
  end

  def new
    @search = Search.new
  end

  def create
    @search = Search.find_or_initialize_by(create_params.to_h.symbolize_keys.compact_blank)
    @search.requests_quantity += 1 if Search.exists?(@search.id)
    @search.save!

    redirect_to cars_path(create_params)
  end

  private

  def create_params
    params.require(:search).permit(:make, :model, :year_from, :year_to, :price_from, :price_to)
      .with_defaults(user_id: current_user&.id)
  end

  def query_params
    params.permit(:page, :items)
  end

  def user_searches
    @user_searches ||= current_user.searches
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:order_by] && params[:direction] == 'ASC' ? 'DESC' : 'ASC'
    link_to title, request.params.merge(order_by: column, direction:)
  end

  def locale_options
    I18n.available_locales.map { |locale| [I18n.t(locale), locale] }
  end

  def switch_locale_path(locale)
    url_for(controller: controller_name, action: action_name, locale:)
  end
end

app/views/cars/index.html.slim
= link_to t('helpers.link.back'), root_path
- if %i[make model year_from year_to price_from price_to].all? { |k| params.key? k }
  h3 = t('.search.title')
  li = t('.search.make', parameter: params[:make])
  li = t('.search.model', parameter: params[:model])
  li = t('.search.price_from', parameter: params[:price_from])
  li = t('.search.price_to', parameter: params[:price_to])
  li = t('.search.year_from', parameter: params[:year_from])
  li = t('.search.year_to', parameter: params[:year_to])
h1 = t('cars.index.title')
table[style="width:100%"]
  thead
    tr
      th №
      th = t('.make')
      th = t('.model')
      th = sortable 'year', t('.year')
      th = sortable 'odometer', t('.odometer')
      th = sortable 'price', t('.price')
      th = t('.description')
      th = sortable 'created_at', t('.added_at')
  tbody
    - @cars_collection.records.each.with_index(1) do |car, index|
      tr
        td= index
        td= car.make
        td= car.model
        td= car.year
        td= car.odometer
        td= car.price
        td= car.description
        td= car.created_at
div[style="display:flex; justify-content:space-between; align-items:center"]
  h3 = t('.total_count', count: @cars_collection.pagy.count)
  == pagy_nav(@cars_collection.pagy, i18n_key: 'pagy.nav')

app/views/homes/index.html.slim
h1 Hello World!
ul
  li = link_to 'Help', helps_path
  li = link_to 'Cars list', cars_path
  li = link_to 'Search', new_search_path
  - if user_signed_in?
    li = link_to 'My searches', searches_path
    li = button_to 'Sign Out', destroy_user_session_path, method: :delete
  - else
    li = link_to 'Sign Up', new_user_registration_path
    li = link_to 'Sign In', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title CarsAdvertisements
    meta[name="viewport" content="width=device-width,initial-scale=1"]
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag "application"
  body
    = render 'shared/change_locale'
    = render 'shared/flash'
    = yield

app/views/searches/_form.html.slim
= form_with model: @search do |f|
  = f.search_field :make, placeholder: t('.make')
  = f.search_field :model, placeholder: t('.model')
  = f.number_field :year_from, min: 0, placeholder: t('.year_from')
  = f.number_field :year_to, min: 0, placeholder: t('.year_to')
  = f.number_field :price_from, min: 0, placeholder: t('.price_from')
  = f.number_field :price_to, min: 0, placeholder: t('.price_to')
  = f.submit t('.search_btn')

app/views/searches/index.html.slim
= link_to t('helpers.link.back'), root_path
h1 = t('.title')
table[style="width:100%"]
  thead
    tr
      th №
      th = t('.make')
      th = t('.model')
      th = t('.year_from')
      th = t('.year_to')
      th = t('.price_from')
      th = t('.price_to')
      th = t('.request_quantity')
  tbody
    - @user_search_collection.records.each.with_index(1) do |search, index|
      tr
        td= index
        td= search.make
        td= search.model
        td= search.year_from
        td= search.year_to
        td= search.price_from
        td= search.price_to
        td= search.requests_quantity
div[style="display:flex; justify-content:space-between; align-items:center"]
  h3 = t('.total_count', count: @user_search_collection.pagy.count)
  == pagy_nav(@user_search_collection.pagy)

app/views/searches/new.html.slim
= link_to t('helpers.link.back'), root_path
h1 = t('.title')
= render 'form'

app/views/shared/_change_locale.html.slim
span = t('.select_locale')
ul
  - I18n.available_locales.each.with_index(1) do |locale, index|
    li
      - if I18n.locale == locale
        span = t(locale)
      - else
        = link_to t(locale), switch_locale_path(locale)

app/views/shared/_flash.html.slim
- if notice
  p.notice
    = notice
- if alert
  p.alert
    = alert

app/views/static_pages/help.html.slim
= link_to t('helpers.link.back'), root_path
h1 = t('.title')
table
  thead
    tr
      th = t('.option')
      th = t('.description')
  tbody
    tr
      td = t('menu.help_option')
      td.description = t('menu.help_description')
    tr
      td = t('menu.cars_list_option')
      td.description = t('menu.cars_list_description')
    tr
      td = t('menu.search_option')
      td.description = t('menu.search_description')
    tr
      td = t('menu.user_searches_option')
      td.description = t('menu.user_searches_description')
    tr
      td = t('menu.sign_in_option')
      td.description = t('menu.sign_in_description')
    tr
      td = t('menu.sign_up_option')
      td.description = t('menu.sign_up_description')
    tr
      td = t('menu.sign_out_btn')
      td.description = t('menu.sign_out_description')

app/views/static_pages/home.html.slim
h1 = t('hello')
ul
  li = link_to t('menu.help_option'), help_path
  li = link_to t('menu.cars_list_option'), cars_path
  li = link_to t('menu.search_option'), new_search_path
  - if user_signed_in?
    li = link_to t('menu.user_searches_option'), searches_path
    li = button_to t('menu.sign_out_btn'), destroy_user_session_path, method: :delete
  - else
    li = link_to t('menu.sign_up_option'), new_user_registration_path
    li = link_to t('menu.sign_in_option'), new_user_session_path